# Generated by Django 5.1.2 on 2024-10-26 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_registration_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='mobile_number',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
