# Generated by Django 5.1.2 on 2024-10-26 16:52

import Form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_alter_registration_model_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='mobile_number',
            field=models.IntegerField(validators=[Form.models.mobile_number_validator]),
        ),
    ]
