# Generated by Django 5.1.2 on 2024-10-28 00:48

import Form.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_alter_registration_model_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Already Registered!'}, max_length=254, unique=True, validators=[Form.models.emailDomainValidator]),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
