# Generated by Django 5.1.2 on 2024-10-28 16:51

import Form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_alter_registration_model_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='mobile_number',
            field=models.IntegerField(validators=[Form.models.mobile_number_validator]),
        ),
    ]
